export const categories = [
  {
    slug: "health",
    name: "醫療健康",
    icon: "health",
    emoji: "🏥",
    color: "#B45309",
    sortOrder: 1,
    subcategories: [
      { slug: "ltc-1966",    name: "長照1966" },
      { slug: "health-checkup", name: "成人健檢" },
      { slug: "cancer-screen",  name: "癌症篩檢" },
      { slug: "chronic",        name: "慢性病" },
      { slug: "dementia",       name: "失智照護" },
      { slug: "rehab-bus",      name: "復康巴士" },
      { slug: "accessible-taxi", name: "無障礙計程車" },
      { slug: "assistive",      name: "輔具" },
      { slug: "vaccine",        name: "疫苗" },
      { slug: "drug-delivery",  name: "送藥到家" },
      { slug: "first-aid",      name: "急救" },
    ],
  },
  {
    slug: "transport",
    name: "交通接駁",
    icon: "transport",
    emoji: "🚌",
    color: "#0369A1",
    sortOrder: 2,
    subcategories: [
      { slug: "happy-bus",      name: "幸福巴士" },
      { slug: "rehab-bus",      name: "復康巴士" },
      { slug: "ltc-transport",  name: "長照接送" },
      { slug: "accessible-taxi", name: "無障礙計程車" },
      { slug: "rideshare",      name: "偏鄉共乘" },
      { slug: "elder-card",     name: "敬老卡" },
      { slug: "license",        name: "駕照" },
    ],
  },
  {
    slug: "housing",
    name: "居住安全",
    icon: "housing",
    emoji: "🏠",
    color: "#15803D",
    sortOrder: 3,
    subcategories: [
      { slug: "fall-prevention",  name: "防跌" },
      { slug: "emergency-rescue", name: "緊急救援" },
      { slug: "home-care-worker", name: "居服員" },
      { slug: "repair-subsidy",   name: "修繕補助" },
      { slug: "electric-safety",  name: "用電安全" },
      { slug: "plumber",          name: "水電行" },
      { slug: "social-housing",   name: "社會住宅" },
      { slug: "rent-help",        name: "租屋協助" },
      { slug: "disaster",         name: "防災" },
    ],
  },
  {
    slug: "finance",
    name: "經濟財務",
    icon: "finance",
    emoji: "💰",
    color: "#C2410C",
    sortOrder: 4,
    subcategories: [
      { slug: "anti-fraud",    name: "防詐騙" },
      { slug: "inheritance",   name: "財產繼承" },
      { slug: "will",          name: "預立遺囑" },
      { slug: "trust",         name: "安養信託" },
      { slug: "reverse-mtg",  name: "以房養老" },
      { slug: "asset-mgmt",   name: "財產管理" },
    ],
  },
  {
    slug: "subsidy",
    name: "補助申請",
    icon: "coin",
    emoji: "🪙",
    color: "#7C3AED",
    sortOrder: 5,
    subcategories: [
      { slug: "elder-allowance", name: "老人津貼" },
      { slug: "low-income",      name: "中低收入" },
      { slug: "national-pension", name: "國民年金" },
      { slug: "disability",      name: "身障補助" },
      { slug: "major-illness",   name: "重大傷病" },
      { slug: "elder-card",      name: "敬老卡" },
      { slug: "emergency-aid",   name: "急難救助" },
    ],
  },
  {
    slug: "social",
    name: "社會資源",
    icon: "social",
    emoji: "🤝",
    color: "#7E22CE",
    sortOrder: 6,
    subcategories: [
      { slug: "mental-consult",   name: "心理諮詢" },
      { slug: "visit-care",       name: "關懷訪視" },
      { slug: "solo-elder",       name: "獨居關懷" },
      { slug: "dementia-consult", name: "失智諮詢" },
      { slug: "caregiver-support", name: "照顧者支援" },
      { slug: "respite",          name: "喘息服務" },
      { slug: "domestic-violence", name: "家暴專線" },
      { slug: "legal",            name: "法律諮詢" },
      { slug: "meal-delivery",    name: "送餐服務" },
      { slug: "volunteer",        name: "志工陪伴" },
    ],
  },
  {
    slug: "leisure",
    name: "休閒活動",
    icon: "leisure",
    emoji: "🌸",
    color: "#BE185D",
    sortOrder: 7,
    subcategories: [
      { slug: "community-station", name: "社區據點" },
      { slug: "community-meal",    name: "共餐" },
      { slug: "exercise-class",    name: "運動課程" },
      { slug: "senior-school",     name: "長青學苑" },
      { slug: "volunteer-act",     name: "志工參與" },
      { slug: "silver-travel",     name: "銀髮旅遊" },
      { slug: "board-games",       name: "桌遊團康" },
    ],
  },
  {
    slug: "education",
    name: "教育進修",
    icon: "education",
    emoji: "📚",
    color: "#0E7490",
    sortOrder: 8,
    subcategories: [
      { slug: "elder-university",  name: "樂齡大學" },
      { slug: "elder-center",      name: "樂齡學習中心" },
      { slug: "community-college", name: "社區大學" },
      { slug: "smartphone",        name: "3C手機教學" },
      { slug: "second-career",     name: "二度就業" },
      { slug: "library",           name: "圖書館" },
    ],
  },
] as const;

export type CategorySlug = (typeof categories)[number]["slug"];
