export const categories = [
  {
    slug: "health",
    name: "醫療健康",
    icon: "heart",
    emoji: "🏥",
    color: "#B45309",
    sortOrder: 1,
    subcategories: [
      { slug: "accessible-taxi", name: "無障礙計程車" },
      { slug: "rehab-bus", name: "復康巴士" },
      { slug: "private-ambulance", name: "民間救護車" },
      { slug: "ltc-1966", name: "1966 長照服務" },
      { slug: "day-care", name: "日照中心" },
      { slug: "assistive-device", name: "輔具申請" },
      { slug: "presbyopia-hearing-denture-aid", name: "老花眼鏡、助聽器、假牙補助" },
      { slug: "vaccine-info", name: "疫苗資訊" },
      { slug: "nearby-clinic", name: "鄰近醫學中心、診所" },
      { slug: "health-checkup", name: "健康檢查" },
      { slug: "health-edu", name: "衛教與流行病資訊" },
      { slug: "drug-delivery", name: "藥物送到家" },
      { slug: "advance-decision", name: "預立醫療決定書" },
      { slug: "first-aid", name: "急救處置" },
    ],
  },
  {
    slug: "transport",
    name: "交通接駁",
    icon: "bus",
    emoji: "🚌",
    color: "#0369A1",
    sortOrder: 2,
    subcategories: [
      { slug: "elder-card", name: "敬老卡教學" },
      { slug: "happy-bus", name: "幸福小黃／巴士" },
      { slug: "pupu-rideshare", name: "噗噗共乘" },
      { slug: "ltc-transport", name: "長照交通接送" },
      { slug: "accessible-taxi", name: "無障礙計程車" },
      { slug: "rehab-bus-booking", name: "復康巴士預約" },
      { slug: "license-renewal", name: "駕照更換（監理站）" },
      { slug: "road-safety", name: "行車安全（路老師）" },
    ],
  },
  {
    slug: "housing",
    name: "居住安全",
    icon: "home",
    emoji: "🏠",
    color: "#15803D",
    sortOrder: 3,
    subcategories: [
      { slug: "fall-prevention", name: "防跌施工（裝扶手）" },
      { slug: "solo-elder-alarm", name: "獨居警報申請" },
      { slug: "home-care-worker", name: "居服員申請" },
      { slug: "repair-subsidy", name: "修繕補助" },
      { slug: "nearby-utility", name: "附近水電行" },
      { slug: "earthquake-prep", name: "地震準備" },
      { slug: "fire-prevention", name: "消防檢查與火災預防" },
      { slug: "electric-safety", name: "用電安全與檢測" },
      { slug: "urban-renewal", name: "都市更新" },
      { slug: "social-housing", name: "社會住宅" },
      { slug: "rent-agency", name: "包租代管" },
      { slug: "tsuei-mama", name: "崔媽媽基金會" },
    ],
  },
  {
    slug: "finance",
    name: "經濟財務",
    icon: "wallet",
    emoji: "💰",
    color: "#C2410C",
    sortOrder: 4,
    subcategories: [
      { slug: "elder-pension", name: "老人年金（重陽禮金）" },
      { slug: "anti-fraud", name: "防詐騙電話與案例" },
      { slug: "emergency-subsidy", name: "緊急或日常補助申請" },
      { slug: "inheritance", name: "財產繼承" },
      { slug: "will-prep", name: "預立遺囑" },
      { slug: "asset-management", name: "財產管理" },
      { slug: "elder-trust", name: "安養信託" },
      { slug: "finance-course", name: "理財投資課程" },
    ],
  },
  {
    slug: "social",
    name: "社會資源",
    icon: "users",
    emoji: "🤝",
    color: "#7E22CE",
    sortOrder: 5,
    subcategories: [
      { slug: "welfare-consult", name: "社會福利諮詢" },
      { slug: "mental-hotline", name: "心理諮詢專線" },
      { slug: "psych-clinic", name: "附近的身心科" },
      { slug: "domestic-violence", name: "家暴專線" },
      { slug: "elder-center", name: "長青中心" },
      { slug: "meal-delivery", name: "送餐服務" },
      { slug: "legal-consult", name: "法律諮詢" },
      { slug: "laf", name: "法扶基金會" },
    ],
  },
  {
    slug: "leisure",
    name: "休閒活動",
    icon: "smile",
    emoji: "🌸",
    color: "#BE185D",
    sortOrder: 6,
    subcategories: [
      { slug: "community-station", name: "社區據點活動" },
      { slug: "community-meal", name: "社區共餐活動" },
      { slug: "volunteer", name: "志工參與" },
      { slug: "elder-exercise", name: "長者運動建議" },
      { slug: "silver-travel", name: "銀髮旅遊" },
      { slug: "activity-subsidy", name: "活動補助" },
    ],
  },
  {
    slug: "education",
    name: "教育進修",
    icon: "book",
    emoji: "📚",
    color: "#0E7490",
    sortOrder: 7,
    subcategories: [
      { slug: "elder-university", name: "樂齡大學／社區大學" },
      { slug: "second-career", name: "二次就業" },
      { slug: "digital-tutorial", name: "3C 教學影片" },
    ],
  },
] as const;

export type CategorySlug = (typeof categories)[number]["slug"];
